apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipeline-walberrrr
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: rfp-vivo-2023
    github.com/project-slug: headllama/pipeline-walberrrr
  tags:
      - frontend
      - react
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: WebApp
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: user:default/guest
  system: system:default/coe
  consumesApis: []
